version: 2.1

jobs:
  #
  # Build and Deploy www.cronops.io
  #
  build-deploy-gh-pages:
    machine:
      image: ubuntu-1604:202007-01 # Ubuntu 16.04, Docker v19.03.12, Docker Compose v1.26.1

      # This job has been blocked because Docker Layer Caching is not available on your plan.
      # Should upgrade if necessary.
      docker_layer_caching: false

    steps:
      - checkout

      - run:
          name: Context Info Cmds
          command: pwd && ls -ltra && git branch

      - run:
          name: Installing Pre-requisites
          command: |
            sudo apt-get update
            sudo apt-get -y upgrade docker-ce
            docker --version # Docker version 19.03.12, build 48a66213fe

      - run:
          name: Initialize Repo Makefiles
          command: |
            make init-makefiles
            git update-index --assume-unchanged "Makefile"

      - run:
          name: Build
          command: make build-dist

      - run:
          name: Deploy
          command: |
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global user.name "$GIT_USER_NAME"
            make deploy-dist-github

  #
  # Release
  #
  release-version-with-changelog:
    machine:
      image: ubuntu-1604:202007-01
      docker_layer_caching: false

    environment:
      VERSION_NUMBER: patch # opts: patch, minor or major.

    steps:
      - checkout

      - run:
          name: Context Info Cmds
          command: pwd && ls -ltra && git branch

      - run:
          name: Initialize Repo Makefiles
          command: |
            make init-makefiles
            git update-index --assume-unchanged "Makefile"

      - run:
          name: Release New Version
          command: |
            if git status | grep 'nothing to commit, working tree clean'; then
              echo "==============================================================================================="
              echo "release-$VERSION_NUMBER-with-changelog-circleci"
              echo "==============================================================================================="
              git config --global user.email "$GIT_USER_EMAIL"
              git config --global user.name "$GIT_USER_NAME"
              make release-$VERSION_NUMBER-with-changelog-circleci
            else
              echo "==============================================================================================="
              echo "Changes in working directory pending to be pushed - please check 'git status' cmd output below "
              echo "==============================================================================================="
              echo "$(git status)"
              echo "==============================================================================================="
            fi

#
# Jobs workflow
#
workflows:
  version: 2
  test_and_release:
    jobs:
      - build-deploy-gh-pages:
          context: cronops-org-global-context
          filters:
            branches:
             only: # only branches matching the below regex filters will run
               - master
      - release-version-with-changelog:
          context: cronops-org-global-context
          requires:
            - build-deploy-gh-pages
          filters:
            branches:
             only: # only branches matching the below regex filters will run
               - master
